# Generated by Django 4.0.5 on 2022-07-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW5App', '0002_remove_course_files_remove_course_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
