# Generated by Django 4.0.5 on 2022-07-03 20:48

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HW5App', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutorial_Video',
            field=embed_video.fields.EmbedVideoField(default='hello'),
            preserve_default=False,
        ),
    ]
