# Generated by Django 4.0.5 on 2022-07-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW5App', '0005_course_tutorial_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videodescription',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
