# Generated by Django 4.0.5 on 2022-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW5App', '0008_quiz_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
